// ─────────────────────────────────────────────────────────────────
// Concept entity map per category and subcategory.
//
// Each hub page (/[category], /[category]/[subcategory]) emits
// `about` and `mentions` arrays of concept-entity @ids pulled from
// this map. Concept entities are canonically declared at
// https://www.vastucart.in/concepts/{slug}#entity per contract §3.
//
// Also maps subcategory slugs to the glossary terms they use, so
// the hub page can emit relevant DefinedTerm schema.
// ─────────────────────────────────────────────────────────────────

export const CATEGORY_CONCEPT_SLUGS: Record<string, string[]> = {
  jyotish: [
    "surya",
    "chandra",
    "mangala",
    "budha",
    "brihaspati",
    "shukra",
    "shani",
    "rahu",
    "ketu",
  ],
  numerology: [
    "life-path-number",
    "destiny-number",
    "soul-urge-number",
    "expression-number",
    "birthday-number",
    "master-numbers",
    "chaldean-numerology",
    "pythagorean-numerology",
  ],
  tarot: [
    "major-arcana",
    "minor-arcana",
    "suit-of-wands",
    "suit-of-cups",
    "suit-of-swords",
    "suit-of-pentacles",
    "court-cards",
    "rider-waite-deck",
  ],
  vastu: [
    "vastu-purusha-mandala",
    "brahmasthana",
    "pancha-bhutas",
    "eight-directions",
  ],
  puja: [],
  festivals: [],
  gemstones: [],
  rudraksha: [],
};

export const SUBCATEGORY_CONCEPT_SLUGS: Record<string, string[]> = {
  // jyotish subcategories
  "jyotish/graha-in-bhava": [
    "surya",
    "chandra",
    "mangala",
    "budha",
    "brihaspati",
    "shukra",
    "shani",
    "rahu",
    "ketu",
    "tanu-bhava",
    "dhana-bhava",
    "sahaja-bhava",
    "sukha-bhava",
    "putra-bhava",
    "ripu-bhava",
    "kalatra-bhava",
    "ayush-bhava",
    "dharma-bhava",
    "karma-bhava",
    "labha-bhava",
    "vyaya-bhava",
  ],
  "jyotish/graha-states": [
    "surya",
    "chandra",
    "mangala",
    "budha",
    "brihaspati",
    "shukra",
    "shani",
    "rahu",
    "ketu",
  ],
  "jyotish/lagna-profiles": [
    "tanu-bhava",
    "mesha",
    "vrishabha",
    "mithuna",
    "karka",
    "simha",
    "kanya",
    "tula",
    "vrishchika",
    "dhanu",
    "makara",
    "kumbha",
    "meena",
  ],
  "jyotish/rashi-profiles": [
    "mesha",
    "vrishabha",
    "mithuna",
    "karka",
    "simha",
    "kanya",
    "tula",
    "vrishchika",
    "dhanu",
    "makara",
    "kumbha",
    "meena",
  ],
  "jyotish/nakshatra": [
    "ashwini",
    "bharani",
    "krittika",
    "rohini",
    "mrigashira",
    "ardra",
    "punarvasu",
    "pushya",
    "ashlesha",
    "magha",
    "purva-phalguni",
    "uttara-phalguni",
    "hasta",
    "chitra",
    "swati",
    "vishakha",
    "anuradha",
    "jyeshtha",
    "mula",
    "purva-ashadha",
    "uttara-ashadha",
    "shravana",
    "dhanishta",
    "shatabhisha",
    "purva-bhadrapada",
    "uttara-bhadrapada",
    "revati",
  ],
  "jyotish/dasha": [],
  "jyotish/yogas": [
    "raj-yoga",
    "dhana-yoga",
    "gaja-kesari-yoga",
    "pancha-mahapurusha-yoga",
    "hamsa-yoga",
    "malavya-yoga",
    "ruchaka-yoga",
    "bhadra-yoga",
    "sasa-yoga",
    "neecha-bhanga-raja-yoga",
    "vipareeta-raja-yoga",
  ],
  "jyotish/remedies": [],
  "jyotish/conjunctions": [
    "surya",
    "chandra",
    "mangala",
    "budha",
    "brihaspati",
    "shukra",
    "shani",
    "rahu",
    "ketu",
  ],

  // numerology
  "numerology/life-path": ["life-path-number"],
  "numerology/destiny-number": ["destiny-number", "expression-number"],
  "numerology/name-numerology": [
    "pythagorean-numerology",
    "chaldean-numerology",
  ],
  "numerology/angel-numbers": [],
  "numerology/mobile-numerology": [],
  "numerology/house-number": [],
  "numerology/dob-analysis": ["birthday-number", "life-path-number"],

  // tarot
  "tarot/major-arcana": ["major-arcana", "rider-waite-deck"],
  "tarot/minor-arcana": [
    "minor-arcana",
    "suit-of-wands",
    "suit-of-cups",
    "suit-of-swords",
    "suit-of-pentacles",
    "rider-waite-deck",
  ],
  "tarot/tarot-spreads": ["major-arcana", "minor-arcana"],
  "tarot/tarot-by-zodiac": [],
  "tarot/yes-no-tarot": [],
  "tarot/love-tarot": [],
  "tarot/career-tarot": [],

  // vastu
  "vastu/directions": ["eight-directions", "pancha-bhutas"],
  "vastu/rooms": ["vastu-purusha-mandala"],
  "vastu/entrance": ["eight-directions"],
  "vastu/remedies-vastu": [],
  "vastu/yantras": [],
  "vastu/plants-vastu": [],
  "vastu/colours-vastu": ["pancha-bhutas"],

  // puja + festivals + gemstones + rudraksha: concepts attach per-post rather than per-sub
  "puja/graha-puja": [
    "surya",
    "chandra",
    "mangala",
    "budha",
    "brihaspati",
    "shukra",
    "shani",
    "rahu",
    "ketu",
  ],
  "puja/deity-puja": [],
  "puja/vrat": [],
  "puja/havan": [],
  "puja/daily-puja": [],
  "festivals/major-festivals": [],
  "festivals/ekadashi": [],
  "festivals/amavasya": [],
  "festivals/purnima": [],
  "festivals/navratri": [],
  "gemstones/by-planet": [
    "surya",
    "chandra",
    "mangala",
    "budha",
    "brihaspati",
    "shukra",
    "shani",
    "rahu",
    "ketu",
  ],
  "gemstones/by-lagna": [
    "mesha",
    "vrishabha",
    "mithuna",
    "karka",
    "simha",
    "kanya",
    "tula",
    "vrishchika",
    "dhanu",
    "makara",
    "kumbha",
    "meena",
  ],
  "gemstones/combinations": [],
  "gemstones/buying-guide": [],
  "rudraksha/by-mukhi": [],
  "rudraksha/by-planet": [
    "surya",
    "chandra",
    "mangala",
    "budha",
    "brihaspati",
    "shukra",
    "shani",
    "rahu",
    "ketu",
  ],
  "rudraksha/by-lagna": [
    "mesha",
    "vrishabha",
    "mithuna",
    "karka",
    "simha",
    "kanya",
    "tula",
    "vrishchika",
    "dhanu",
    "makara",
    "kumbha",
    "meena",
  ],
};

export function getCategoryConceptSlugs(categorySlug: string): string[] {
  return CATEGORY_CONCEPT_SLUGS[categorySlug] ?? [];
}

export function getSubcategoryConceptSlugs(
  categorySlug: string,
  subcategorySlug: string
): string[] {
  return SUBCATEGORY_CONCEPT_SLUGS[`${categorySlug}/${subcategorySlug}`] ?? [];
}
