#!/usr/bin/env tsx
// ─────────────────────────────────────────────────────────────────
// swap-infographics-to-figures.ts
//
// Replaces generic unDraw `infographic` content blocks with proper
// `image-figure` content blocks pointing to the new composed-SVG
// infographic cards generated by scripts/generate-infographic-cards.
//
// For each Jyotish post:
//   1. Find all `infographic` blocks (the generic unDraw ones).
//   2. Determine whether the slot is the career or the remedies
//      slot (heuristic: first generic infographic → career; second
//      → remedies; mapped by adjacent block context).
//   3. Replace each with an `image-figure` block referencing the
//      matching {slug}-career-infographic.webp / {slug}-remedies-
//      infographic.webp file.
//   4. Adds the new files to image_manifest with proper alt and
//      ImageObject schema metadata.
//
// Idempotent — skips posts that already have the new image-figure
// blocks at those slots.
//
// Usage:
//   npx tsx scripts/swap-infographics-to-figures.ts                # dry
//   npx tsx scripts/swap-infographics-to-figures.ts --apply        # write
// ─────────────────────────────────────────────────────────────────

import fs from "node:fs";
import path from "node:path";

interface Options {
  apply: boolean;
  slug?: string;
}

const CONTENT_DIR = path.join(process.cwd(), "content");
const POSTS_PUBLIC_DIR = path.join(process.cwd(), "public", "posts");

const PLANET_ENGLISH: Record<string, string> = {
  surya: "Sun",
  chandra: "Moon",
  mangal: "Mars",
  budha: "Mercury",
  guru: "Jupiter",
  shukra: "Venus",
  shani: "Saturn",
  rahu: "Rahu",
  ketu: "Ketu",
};

const HOUSE_SANSKRIT: Record<number, string> = {
  1: "Pratham Bhava",
  2: "Dhana Bhava",
  3: "Parakrama Bhava",
  4: "Sukha Sthana",
  5: "Putra Bhava",
  6: "Ripu Bhava",
  7: "Yuvati Bhava",
  8: "Randhra Bhava",
  9: "Dharma Bhava",
  10: "Karma Bhava",
  11: "Labha Bhava",
  12: "Vyaya Bhava",
};

interface Block {
  type: string;
  illustration?: string;
  filename?: string;
  eyebrow?: string;
  heading?: string;
  alt?: string;
  caption?: string;
  width?: number;
  height?: number;
  priority?: boolean;
  credit?: string;
  [k: string]: unknown;
}

interface ManifestEntry {
  filename: string;
  alt: string;
  caption?: string;
  width: number;
  height: number;
  format: string;
  style?: string;
}

interface Post {
  slug: string;
  category?: string;
  planet_id?: string;
  house_number?: number;
  lagna_id?: string;
  image_manifest?: ManifestEntry[];
  content: Block[];
}

// Decide whether the infographic slot at index i is "career" or
// "remedies" by looking at the heading of the nearest preceding
// scannable-prose / prose block.
function classifySlot(content: Block[], idx: number): "career" | "remedies" {
  for (let j = idx - 1; j >= 0; j--) {
    const b = content[j];
    if (
      b.type === "scannable-prose" ||
      b.type === "prose" ||
      b.type === "effects-grid"
    ) {
      const heading = String(b.heading ?? "");
      if (/career|vocation|livelihood/i.test(heading)) return "career";
      if (/remed|daily practice/i.test(heading)) return "remedies";
      // effects-grid is treated as career-adjacent
      if (b.type === "effects-grid") return "career";
    }
  }
  return "career";
}

function buildFigureBlock(
  post: Post,
  kind: "career" | "remedies"
): Block | null {
  if (!post.planet_id || !post.house_number) return null;
  const planet = PLANET_ENGLISH[post.planet_id] ?? post.planet_id;
  const houseLabel = `${post.house_number}${ordinalSuffix(post.house_number)} house`;
  const sanskrit = HOUSE_SANSKRIT[post.house_number] ?? "";
  const filename = `${post.slug}-${kind}-infographic.webp`;
  const filePath = path.join(POSTS_PUBLIC_DIR, post.slug, filename);
  if (!fs.existsSync(filePath)) return null;

  const alt =
    kind === "career"
      ? `${planet} in ${houseLabel} career fits infographic for Mesh Lagna natives, six career paths with brand-coloured icons`
      : `${planet} ${houseLabel} remedies infographic showing mantra, gemstone, day, colour, yantra, and donation`;
  const caption =
    kind === "career"
      ? `Career fits the chart structurally rewards. Built from classical Parashari tradition.`
      : `Daily practice protocol pulled from the post body and the Vimshottari dasha mechanics.`;
  return {
    type: "image-figure",
    filename,
    alt,
    caption,
    width: 1200,
    height: 800,
    priority: false,
    credit: "VastuCart",
  };
}

function ordinalSuffix(n: number): string {
  const j = n % 10;
  const k = n % 100;
  if (j === 1 && k !== 11) return "st";
  if (j === 2 && k !== 12) return "nd";
  if (j === 3 && k !== 13) return "rd";
  return "th";
}

function ensureManifest(
  post: Post,
  kind: "career" | "remedies"
): boolean {
  const filename = `${post.slug}-${kind}-infographic.webp`;
  if (!post.image_manifest) post.image_manifest = [];
  if (post.image_manifest.find((m) => m.filename === filename)) return false;
  const planet = PLANET_ENGLISH[post.planet_id ?? ""] ?? "";
  const houseLabel = post.house_number
    ? `${post.house_number}${ordinalSuffix(post.house_number)} house`
    : "house";
  const alt =
    kind === "career"
      ? `${planet} in ${houseLabel} career fits infographic — six career paths with brand-coloured icons`
      : `${planet} ${houseLabel} remedies infographic — mantra, gemstone, day, colour, yantra, donation`;
  post.image_manifest.push({
    filename,
    alt,
    caption:
      kind === "career"
        ? "Career fits derived from classical Parashari tradition."
        : "Daily practice protocol distilled into a six-card panel.",
    width: 1200,
    height: 800,
    format: "webp",
    style: "composed Vedic infographic, brand-coloured",
  });
  return true;
}

function migratePost(post: Post): { changed: boolean; post: Post } {
  if (post.category !== "jyotish") return { changed: false, post };
  if (!Array.isArray(post.content)) return { changed: false, post };
  let changed = false;

  // Pass 1: collect indices of generic infographic blocks
  const indices: number[] = [];
  for (let i = 0; i < post.content.length; i++) {
    if (post.content[i].type === "infographic") indices.push(i);
  }
  if (indices.length === 0) return { changed: false, post };

  // Pass 2: for each generic infographic, replace in place with the
  // matching image-figure block. Track which kinds we've used so we
  // do not double-up.
  const usedKinds = new Set<"career" | "remedies">();
  for (const idx of indices) {
    let kind = classifySlot(post.content, idx);
    if (usedKinds.has(kind)) {
      // Use the other kind if this one is taken
      kind = kind === "career" ? "remedies" : "career";
    }
    if (usedKinds.has(kind)) continue; // both used already
    const figure = buildFigureBlock(post, kind);
    if (!figure) continue;
    post.content[idx] = figure;
    usedKinds.add(kind);
    ensureManifest(post, kind);
    changed = true;
  }

  // If neither kind was used (generic infographics had no slot
  // context), append career as the first one.
  return { changed, post };
}

function walk(dir: string, cb: (file: string) => void): void {
  if (!fs.existsSync(dir)) return;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, cb);
    else cb(full);
  }
}

function parseArgs(): Options {
  const args = process.argv.slice(2);
  const opts: Options = { apply: false };
  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--apply") opts.apply = true;
    else if (args[i] === "--slug" && args[i + 1]) {
      opts.slug = args[i + 1];
      i++;
    }
  }
  return opts;
}

function main() {
  const opts = parseArgs();
  const files: string[] = [];
  walk(CONTENT_DIR, (f) => {
    if (f.endsWith(".json")) files.push(f);
  });
  let updated = 0;
  let unchanged = 0;
  for (const file of files) {
    let post: Post;
    try {
      post = JSON.parse(fs.readFileSync(file, "utf-8"));
    } catch {
      continue;
    }
    if (opts.slug && post.slug !== opts.slug) continue;
    const { changed } = migratePost(post);
    if (changed) {
      updated++;
      if (opts.apply) {
        fs.writeFileSync(file, JSON.stringify(post, null, 2) + "\n");
      }
      console.log(`  ${opts.apply ? "✓" : "~"} ${path.basename(file)}`);
    } else {
      unchanged++;
    }
  }
  console.log(
    `\n${updated} ${opts.apply ? "swapped" : "would swap"}, ${unchanged} unchanged.`
  );
  if (!opts.apply && updated > 0) {
    console.log(`\nRun with --apply to write changes.`);
  }
}

main();
